spring:
 datasource:
   url: jdbc:mysql://localhost:3306/scnu_nlp?useUnicode=true&characterEncoding=utf8&autoReconnect=true
   username: root
   password: 1017520
   driverClassName: com.mysql.jdbc.Driver

mybatis:
 type-aliases-package: com.nlp.model
 config-location: classpath:mybatis.xml
